ocr/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    DataLimitViewSet, FileLimitViewSet, BlockListViewSet,
    UploadedFileViewSet, SupportTicketViewSet, CSRFView
)

# Create a router and register our viewsets with it
router = DefaultRouter()
router.register(r'data-limits', DataLimitViewSet)
router.register(r'file-limits', FileLimitViewSet)
router.register(r'block-list', BlockListViewSet)
router.register(r'files', UploadedFileViewSet, basename='file')
router.register(r'support-tickets', SupportTicketViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('csrf-token/', CSRFView.as_view(), name='get_csrf_token'),
] 

ocr/application/urls.py
from django.urls import path, include
from . import views
from . import login
from api.urls import urlpatterns as api_urls

app_name = 'application'

urlpatterns = [
    # API endpoints
    path('api/', include(api_urls)),
    
    # Auth endpoints
    path('auth/login/', login.handle_login, name='handle_login'),
    path('auth/register/', login.handle_register, name='handle_register'),
    path('auth/logout/', login.handle_logout, name='handle_logout'),
    path('auth/google/', login.google_auth, name='handle_google_auth'),
    path('auth/google/callback/', login.google_auth_callback, name='google_auth_callback'),

    # This must come last to prevent overriding all other paths
    path('', views.ReactAppView.as_view(), name='react_app'),
]

ocr/ocr/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from application.views import ReactAppView

"""
URL configuration for ocr project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('application.urls')),  # All API routes under /api/
    re_path(r'^.*$', ReactAppView.as_view(), name='react-app'),  # Serve React app for all other routes
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ocr/application/model/craft_text_detector/models/craftnet.py
"""
Copyright (c) 2019-present NAVER Corp.
MIT License
"""

# -*- coding: utf-8 -*-
import torch
import torch.nn as nn
import torch.nn.functional as F

from application.model.craft_text_detector.models.basenet.vgg16_bn import vgg16_bn, init_weights


class double_conv(nn.Module):
    def __init__(self, in_ch, mid_ch, out_ch):
        super(double_conv, self).__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(in_ch + mid_ch, mid_ch, kernel_size=1),
            nn.BatchNorm2d(mid_ch),
            nn.ReLU(inplace=True),
            nn.Conv2d(mid_ch, out_ch, kernel_size=3, padding=1),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
        )

    def forward(self, x):
        x = self.conv(x)
        return x


class CraftNet(nn.Module):
    def __init__(self, pretrained=False, freeze=False):
        super(CraftNet, self).__init__()

        """ Base network """
        self.basenet = vgg16_bn(pretrained, freeze)

        """ U network """
        self.upconv1 = double_conv(1024, 512, 256)
        self.upconv2 = double_conv(512, 256, 128)
        self.upconv3 = double_conv(256, 128, 64)
        self.upconv4 = double_conv(128, 64, 32)

        num_class = 2
        self.conv_cls = nn.Sequential(
            nn.Conv2d(32, 32, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.Conv2d(32, 32, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.Conv2d(32, 16, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.Conv2d(16, 16, kernel_size=1),
            nn.ReLU(inplace=True),
            nn.Conv2d(16, num_class, kernel_size=1),
        )

        init_weights(self.upconv1.modules())
        init_weights(self.upconv2.modules())
        init_weights(self.upconv3.modules())
        init_weights(self.upconv4.modules())
        init_weights(self.conv_cls.modules())

    def forward(self, x):
        """ Base network """
        sources = self.basenet(x)

        """ U network """
        y = torch.cat([sources[0], sources[1]], dim=1)
        y = self.upconv1(y)

        y = F.interpolate(
            y, size=sources[2].size()[2:], mode="bilinear", align_corners=False
        )
        y = torch.cat([y, sources[2]], dim=1)
        y = self.upconv2(y)

        y = F.interpolate(
            y, size=sources[3].size()[2:], mode="bilinear", align_corners=False
        )
        y = torch.cat([y, sources[3]], dim=1)
        y = self.upconv3(y)

        y = F.interpolate(
            y, size=sources[4].size()[2:], mode="bilinear", align_corners=False
        )
        y = torch.cat([y, sources[4]], dim=1)
        feature = self.upconv4(y)

        y = self.conv_cls(feature)

        return y.permute(0, 2, 3, 1), feature


if __name__ == "__main__":
    model = CraftNet(pretrained=True).cuda()
    output, _ = model(torch.randn(1, 3, 768, 768).cuda())
    print(output.shape)

ocr/application/model/craft_text_detector/models/refinenet.py
"""
Copyright (c) 2019-present NAVER Corp.
MIT License
"""

# -*- coding: utf-8 -*-
import torch
import torch.nn as nn
from application.model.craft_text_detector.models.basenet.vgg16_bn import init_weights


class RefineNet(nn.Module):
    def __init__(self):
        super(RefineNet, self).__init__()

        self.last_conv = nn.Sequential(
            nn.Conv2d(34, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),
            nn.Conv2d(64, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),
            nn.Conv2d(64, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),
        )

        self.aspp1 = nn.Sequential(
            nn.Conv2d(64, 128, kernel_size=3, dilation=6, padding=6),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.Conv2d(128, 128, kernel_size=1),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.Conv2d(128, 1, kernel_size=1),
        )

        self.aspp2 = nn.Sequential(
            nn.Conv2d(64, 128, kernel_size=3, dilation=12, padding=12),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.Conv2d(128, 128, kernel_size=1),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.Conv2d(128, 1, kernel_size=1),
        )

        self.aspp3 = nn.Sequential(
            nn.Conv2d(64, 128, kernel_size=3, dilation=18, padding=18),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.Conv2d(128, 128, kernel_size=1),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.Conv2d(128, 1, kernel_size=1),
        )

        self.aspp4 = nn.Sequential(
            nn.Conv2d(64, 128, kernel_size=3, dilation=24, padding=24),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.Conv2d(128, 128, kernel_size=1),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.Conv2d(128, 1, kernel_size=1),
        )

        init_weights(self.last_conv.modules())
        init_weights(self.aspp1.modules())
        init_weights(self.aspp2.modules())
        init_weights(self.aspp3.modules())
        init_weights(self.aspp4.modules())

    def forward(self, y, upconv4):
        refine = torch.cat([y.permute(0, 3, 1, 2), upconv4], dim=1)
        refine = self.last_conv(refine)

        aspp1 = self.aspp1(refine)
        aspp2 = self.aspp2(refine)
        aspp3 = self.aspp3(refine)
        aspp4 = self.aspp4(refine)

        # out = torch.add([aspp1, aspp2, aspp3, aspp4], dim=1)
        out = aspp1 + aspp2 + aspp3 + aspp4
        return out.permute(0, 2, 3, 1)  # , refine.permute(0,2,3,1)

ocr/application/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.core.exceptions import ValidationError
import ipaddress

# Model dataLimit
class dataLimit(models.Model):
    value = models.IntegerField(default=0, help_text="Wartość limitu danych")

    def __str__(self):
        return f"Data limit: {self.value}"

# Model fileLimit
class fileLimit(models.Model):
    value = models.IntegerField(default=0, help_text="Wartość limitu plików")

    def __str__(self):
        return f"File limit: {self.value}"

# Model to store uploaded files
class UploadedFile(models.Model):
    file = models.FileField(upload_to='uploads/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

class SupportTicket(models.Model):
    name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    message = models.TextField()

ocr/application/forms.py
from django import forms
from application.utils import validate_image_file

class UploadFileForm(forms.Form):
    file = forms.FileField(
        validators=[validate_image_file],
        widget=forms.FileInput(attrs={
            'accept': '.png,.jpg,.jpeg,.bmp,.gif,.tiff,.webp'
        })
    )

class SubmitTicketForm(forms.Form):
    name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    message = forms.CharField(widget=forms.Textarea)

ocr/application/views.py
import os
from django.http import HttpResponse
from django.conf import settings
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import ensure_csrf_cookie
from django.template.loader import render_to_string

@method_decorator(ensure_csrf_cookie, name='dispatch')
class ReactAppView(TemplateView):
    template_name = 'index.html'

    def get(self, request, *args, **kwargs):
        try:
            # Get the CSRF token
            csrf_token = request.COOKIES.get('csrftoken', '')
            
            # Render the template with the CSRF token
            html = render_to_string('index.html', {
                'csrf_token': csrf_token,
                'static_url': settings.STATIC_URL,
            })
            
            return HttpResponse(html)
        except Exception as e:
            return HttpResponse(
                """
                <div style="text-align: center; margin-top: 50px;">
                    <h1>Error loading React app</h1>
                    <p>Please make sure the React app is built and the build directory is properly configured.</p>
                    <p>Error details: {}</p>
                </div>
                """.format(str(e))
            )

ocr/application/templates/application/base.html
{% load django_bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block bootstrap5_content %}
<html>
<head>
    <title>File Upload</title>
</head>
<body>
    {% block nav %}{% include 'application/navbar.html' %}{% endblock nav %}
    {% block specific_content %}{% endblock specific_content %}
</body>
</html>
{% endblock bootstrap5_content %}

ocr/application/templates/application/contact.html
{% extends "application/base.html" %}
{% block specific_content %}
<div class="row align-items-center h-50">
<div class="col">
</div>
<div class="col">
    <form method="post" enctype="multipart/form-data" action="/application/contact/">
      <div class="row">
        <div class="col">
          <label for="id-name" class="form-label">Wypełnij formularz zgłoszeniowy</label>
          <input type="text" class="form-control" name="name" placeholder="Name" id="id-name">
        </div>
        <div class="col">
        </div>
      </div>
      <div class="row mt-2">
        <div class="col">
          <input type="text" class="form-control" name="email" placeholder="E-mail">
        </div>
        <div class="col">
        </div>
      </div>
      <div class="row mt-2">
          <div class="form-group">
            <textarea class="form-control" id="textarea" rows="3"></textarea>
          </div>
      </div>
      <button type="submit" class="btn btn-outline-secondary mt-2" id="uploadButton">Upload</button>
    </form>
</div>
<div class="col">
</div>
</div>
{% endblock specific_content %}

ocr/application/templates/application/index.html
{% load django_bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block bootstrap5_content %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Aplikacja OCR</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Strona główna</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Kontakt</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Admin panel</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
{% endblock %}

ocr/application/templates/application/navbar.html
{# Załaduj to, co jest w settings.py pod STATIC_URL #}
{% load static %}
<!-- User Login CSS -->
<style>
  /* Login button styles */
  .login-btn {
    background-color: white;
    border: 1px solid #ddd;
    padding: 8px 16px;
    border-radius: 4px;
    cursor: pointer;
    margin-left: auto;
  }

  /* Google button styles */
  .google-btn {
    background-color: white;
    border: 1px solid #ddd;
    padding: 8px 16px;
    border-radius: 4px;
    cursor: pointer;
    margin-left: 10px;
    display: flex;
    align-items: center;
    gap: 8px;
  }

  /* Modal styles */
  .modal {
    display: none;
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(0,0,0,0.5);
    z-index: 1001;
  }

  .modal-content {
    background-color: white;
    margin: 5% auto;
    padding: 15px;
    width: 350px;
    border-radius: 8px;
    position: relative;
  }

  .close {
    position: absolute;
    right: 20px;
    top: 10px;
    font-size: 24px;
    cursor: pointer;
  }

  /* Tab styles */
  .tab {
    overflow: hidden;
    border-bottom: 1px solid #ddd;
    margin-bottom: 20px;
  }

  .tab button {
    background-color: inherit;
    float: left;
    border: none;
    outline: none;
    cursor: pointer;
    padding: 14px 16px;
    transition: 0.3s;
  }

  .tab button.active {
    border-bottom: 2px solid #0056b3;
    color: #0056b3;
  }

  .tabcontent {
    display: none;
    padding: 6px 12px;
  }

  /* Form styles */
  .form-group {
    margin-bottom: 12px;
  }

  .form-group label {
    display: block;
    margin-bottom: 5px;
  }

  .form-group input {
    width: 100%;
    padding: 6px;
    border: 1px solid #ddd;
    border-radius: 4px;
  }

  .submit-btn {
    width: 100%;
    padding: 8px;
    background-color: #0056b3;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    margin-bottom: 12px;
  }

  body.modal-open {
    overflow: hidden;
  }

  /* Messages styles */
  .messages {
    position: fixed;
    top: 70px;
    right: 20px;
    z-index: 1002;
  }

  .message {
    padding: 10px 20px;
    margin-bottom: 10px;
    border-radius: 4px;
    background-color: #f8d7da;
    color: #721c24;
    border: 1px solid #f5c6cb;
  }

  /* Weird boxes near links deleted */
  .navbar-nav { list-style: none !important; padding-left: 0; }

  .admin-panel-link {
    cursor: pointer;
  }

  .navbar-brand{
      font-size: 1.25rem !important; /* Zmiana font-size z użyciem !important */
      color: rgba(0,0,0, 1) !important;    /* Zmiana koloru z użyciem !important */
  }

  .nav-link{
      color: rgba(0,0,0, 0.65) !important;
      text-decoration: none !important;
      font-size: 1rem !important;
  }
</style>

<!-- Messages -->
{% if messages %}
<div class="messages">
  {% for message in messages %}
    <div class="message">{{ message }}</div>
  {% endfor %}
</div>
{% endif %}

<!-- Navbar HTML -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'application:index' %}">Aplikacja OCR</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'application:contact' %}">Kontakt</a>
        </li>
        <li class="nav-item">
            {% if user.is_authenticated %}
                <a class="nav-link" href="{% if user.is_superuser %}{% url 'admin:index' %}{% else %}#{% endif %}" 
                   onclick="{% if not user.is_superuser %}openPopUp(); event.preventDefault();{% endif %}">
                    Panel administracji
                </a>
                
                {% if not user.is_superuser %}
                    <div id="accessDenied" class="access-denied" style="display:none;">
                        <div class="modal-content">
                            <span class="close" onclick="closePopUp()">&times;</span>
                            <h2>Brak dostępu</h2>
                            <p>Nie masz uprawnień do dostępu do panelu administracyjnego.</p>
                        </div>
                    </div>
                {% endif %}
            {% else %}
                <a class="nav-link admin-panel-link" onclick="openModal()">Panel administracji</a>
            {% endif %}
        </li>
      </ul>
      {% if user.is_authenticated %}
          <span style="margin-right: 1rem;">{{ user.email }}</span>
          <a href="{% url 'application:logout' %}"><button class="btn btn-outline-primary">Logout</button></a>
        {% else %}
          <button class="btn btn-outline-primary" onclick="openModal()">Login</button>
      {% endif %}
    </div>
  </div>
</nav>


<!-- Modal -->
<div id="loginModal" class="modal">
  <div class="modal-content">
    <span class="close" onclick="closeModal()">&times;</span>
    
    <div class="tab">
      <button class="tablinks active" onclick="openTab(event, 'loginTab')">Login</button>
      <button class="tablinks" onclick="openTab(event, 'registerTab')">Register</button>
    </div>

    <div id="loginTab" class="tabcontent" style="display: block;">
      <form action="{% url 'application:handle_login' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="loginEmail">Email</label>
          <input type="email" id="loginEmail" name="email" required>
        </div>
        <div class="form-group">
          <label for="loginPassword">Password</label>
          <input type="password" id="loginPassword" name="password" required>
        </div>
        <button type="submit" class="submit-btn">Login</button>
        <a href="{% url 'application:handle_google_auth' %}" class="google-btn" style="width: 100%; justify-content: center; margin-left: 0;">
          <img src="https://www.google.com/favicon.ico" alt="Google" width="18">
          Login with Google
        </a>
      </form>
    </div>

    <div id="registerTab" class="tabcontent">
      <form action="{% url 'application:handle_register' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="registerEmail">Email</label>
          <input type="email" id="registerEmail" name="email" required>
        </div>
        <div class="form-group">
          <label for="registerPassword">Password</label>
          <input type="password" id="registerPassword" name="password" required>
        </div>
        <div class="form-group">
          <label for="registerConfirmPassword">Confirm Password</label>
          <input type="password" id="registerConfirmPassword" name="confirm_password" required>
        </div>
        <button type="submit" class="submit-btn">Register</button>
        <a href="{% url 'application:handle_google_auth' %}" class="google-btn" style="width: 100%; justify-content: center; margin-left: 0;">
          <img src="https://www.google.com/favicon.ico" alt="Google" width="18">
          Register with Google
        </a>
      </form>
    </div>
  </div>
</div>

<script>
    
function closePopUp() {
    document.getElementById('accessDenied').style.display = 'none';
}

function openPopUp() {
    document.getElementById('accessDenied').style.display = 'block';
}
    
function openModal() {
  document.getElementById('loginModal').style.display = 'block';
  document.body.classList.add('modal-open');
}

function closeModal() {
  document.getElementById('loginModal').style.display = 'none';
  document.body.classList.remove('modal-open');
}

function openTab(evt, tabName) {
  var tabcontent = document.getElementsByClassName("tabcontent");
  for (var i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }

  var tablinks = document.getElementsByClassName("tablinks");
  for (var i = 0; i < tablinks.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" active", "");
  }

  document.getElementById(tabName).style.display = "block";
  evt.currentTarget.className += " active";
}

// Close modal when clicking outside
window.onclick = function(event) {
  var modal = document.getElementById('loginModal');
  if (event.target == modal) {
    modal.style.display = "none";
  }
}

// Auto-hide messages after 5 seconds
document.addEventListener('DOMContentLoaded', function() {
  setTimeout(function() {
    var messages = document.querySelector('.messages');
    if (messages) {
      messages.style.display = 'none';
    }
  }, 5000);
});
</script>

<style>
    .access-denied {
        display: none; /* Hidden by default */
        position: fixed;
        z-index: 1;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgb(0,0,0); 
        background-color: rgba(0,0,0,0.4); /* Black with transparency */
    }

    .modal-content {
        background-color: #fefefe;
        margin: 15% auto;
        padding: 20px;
        border: 1px solid #888;
        width: 80%;
        max-width: 500px;
    }

    .close {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }

    .close:hover,
    .close:focus {
        color: black;
        text-decoration: none;
        cursor: pointer;
    }
</style>

ocr/application/templates/application/upload.html
{% extends "application/base.html" %}
{% block specific_content %}
{#  Wiersz z wyrównaniem do środka, który pionowo zajmuje 50% ekranu (grid system) #}
<div class="row align-items-center h-50">
    {#  Pusta kolumna 1/3  (grid system) #}
    <div class="col">
    </div>
    {#  Kolumna właściwa z zawartością  #}
    <div class="col">
        {#  Div z zawartością obsługującą upload pliku  #}
        <div class="mb-3">
        <form method="post" enctype="multipart/form-data" onsubmit="return validateFile()" id="uploadForm">
            {% csrf_token %}
            {#  W miejsce form.as_p, żeby można było zrobić Bootstrapowy <input> #}
            <label for="formFile" class="form-label">Upload a File</label>
            <input class="form-control" type="file" name="file" accept=".png,.jpg,.jpeg,.bmp,.gif,.tiff,.webp" required="" id="id_file">
            {% if form.errors %}
                <div class="alert alert-danger">
                    {% for field in form %}
                        {% for error in field.errors %}
                            {{ error }}
                        {% endfor %}
                    {% endfor %}
                </div>
            {% endif %}
            {#  mt-3 określa margines od góry, p-1 określa szare pole wokół "Upload" (margin, padding)  #}
            <button type="submit" class="btn btn-secondary mt-3" id="uploadButton">Upload</button>
        </form>
        </div>
        {#  Div z zawartością wyświetlającą pliki po uploadzie, p-0 daje identyczne wyrównanie co Upload  #}
        <div class="container mt-5 p-0">
            <label for="file-list" class="form-label">Uploaded Files</label>
            <ul class="list-group" id="file-list"></ul>
        </div>
        {#  Pop-up wyświetlający się jednokrotnie przy pierwszym uploadzie  #}
        <dialog id="privacyDialog">
            <h3>Privacy Warning</h3>
            <p>Please do not upload any private or sensitive information.</p>
            <div>
                <button id="continueButton">Continue</button>
                <button id="cancelButton">Cancel</button>
            </div>
        </dialog>

        {#  JS przekazujący plik do obsługi przez services/handle_uploaded_file, robi POST na url /api/files co ładuje view  #}
        <script>
            function validateFile() {
                const fileInput = document.querySelector('input[type="file"]');
                const file = fileInput.files[0];
                const allowedExtensions = ['.png', '.jpg', '.jpeg', '.bmp', '.gif', '.tiff', '.webp'];

                if (file) {
                    const fileName = file.name.toLowerCase();
                    if (!allowedExtensions.some(ext => fileName.endsWith(ext))) {
                        alert('Only image files are allowed.');
                        fileInput.value = ''; // Clear the file input
                        return false;
                    }
                }
                return true;
            }

            document.addEventListener("DOMContentLoaded", function () {
                // Dialog elements
                const dialog = document.getElementById("privacyDialog");
                const uploadButton = document.getElementById("uploadButton");
                const continueButton = document.getElementById("continueButton");
                const cancelButton = document.getElementById("cancelButton");
                const uploadForm = document.getElementById("uploadForm");

                let hasShownPrivacyWarning = false;

                // Show dialog on first upload attempt
                // When we refresh it we refresh the "attempt"
                uploadButton.addEventListener("click", function(e) {
                    if (!hasShownPrivacyWarning) {
                        e.preventDefault();
                        dialog.showModal();
                    }
                });

                continueButton.addEventListener("click", function() {
                    hasShownPrivacyWarning = true;
                    //Might add that to cancel as well
                    // Currently it makes warning show up each time we upload
                    dialog.close();
                    uploadForm.submit();
                });

                cancelButton.addEventListener("click", function() {
                    dialog.close();
                });

                fetch("api/files") // Fetch files from Django API
                    .then(response => response.json())
                    .then(files => {
                        const fileList = document.getElementById("file-list");
                        files.forEach(file => {
                        const listItem = document.createElement("li");
                        listItem.className = "list-group-item";
                        // Create a download link for each file
                        const fileLink = document.createElement("a");
                        fileLink.href = `/media/${file}`;
                        fileLink.textContent = file;
                        fileLink.setAttribute("download", file);

                        listItem.appendChild(fileLink);
                        fileList.appendChild(listItem);
                    });
                })
                .catch(error => console.error("Error fetching files:", error));
        });
        </script>
    </div>
    {#  Pusta kolumna 3/3  #}
    <div class="col">
    </div>
</div>
{% endblock specific_content %}